travis:
  secure:
    BINSTAR_TOKEN: X77D2cqf8fx7ixSRjOU1zS2JoelztI8FkX9wfjzCJx0qs0927tqBjzTd/P+vdkt5ybIURC2vsIFR/2/FbQG52B/I/1IxM7SggML7J4SMRguWS+TKMLx03VmyDLlVOO/zp4JQKEpgxcdswHRYe1vTvdhFQZlxCxbMwIzWEEDqtdpPkZMK4Yhx+xNc6xqrkshTus80KvQwzKOG9qHuLpV81b2mR1K/AVzb3LRHKz7hLiDyzACtmNElKzVglEMbW1o3kpGEvqKuqG38M+8BcMife83of7d/+T+Nu2aaLjLatccjEuMAW56ngZH7DbGBfn6tVGJDR1bcA5ra7y9bUO9RCF/eeJ9Va7RajW6BnLJlKTxI5ICKMmfICuhDTVoHuuC1wF/2eM4ziQyJVpVlCk9v8rTxDphZ5gTyjo8TdpcEzRuoxVpWgSm5JAm0J9PHwgeFCLRNh8qYdrUJRwDVPtonan/LwOlP6+1kmLmSVQOBP3AcydD+krLwjZ/Hs/VHzZSmjWAPp05UEwpEulO//bn66+zYevLId3oZqVsYV1aXwbnVHW80gxLRQrpFfuiL3anXWDmEk8I8rgFeBwKlUPao6biSxaC563jNMSnMyvUk3nhSvM8h48rafuWt94+wQLOQS0hMRVA5eJzpsQC555RntuyQp3GNv1DaUZVttaeJmWk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
